name: Code Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install and Run GolangCI-Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
          golangci-lint run ./...
